# もうちょっと効率の良い書き方
#
# このように書けば、
# func.cだけ編集したときにそのファイルだけコンパイルされるので
# 効率がよい。
#
# 実行方法: make -f Makefile.2



hello: func.o main.o
	gcc -Wall -O2 -o hello func.o main.o

func.o: func.c
	gcc -c func.c


main.o: main.c
	gcc -c main.c



