# make cleanを定義する
#
#
# 実行方法: make -f Makefile.3 clean

hello: func.o main.o
	gcc -Wall -O2 -o hello func.o main.o

func.o: func.c
	gcc -c func.c


main.o: main.c
	gcc -c main.c

clean:
	rm *.o hello
